const regionColorMap = {
  "Coast": "#33D0E7",
  "Continent": "#1EB540",
  "Delta": "#8A401F",
  "Depression": "#592914",
  "Desert": "#CDC32C",
  "Dragons-be-here": "#27951F",
  "Foothills": "#BEBB2F",
  "Geoarea": "#9C999B",
  "Gorge": "#C2352B",
  "Island": "#0EC213",
  "Island group": "#398FC2",
  "Isthmus": "#2CBBC2",
  "Lake": "#4879E3",
  "Lowland": "#0CAC08",
  "Pen/cape": "#37A7AC",
  "Peninsula": "#74AC41",
  "Plain": "#E0D044",
  "Plateau": "#E08C1B",
  "Range/mtn": "#E0C5B5",
  "Tundra": "#D5E0CA",
  "Valley": "#7483E0",
  "Wetlands": "#008134"
};

const OD_PAIRS = [
  ['NRT', 'JFK'],
  ['SFO', 'NRT'],
  ['LAX', 'HNL'],
  ['HNL', 'NRT'],
  ['CDG', 'JFK'],
  ['NRT', 'SYD'],
  ['FCO', 'PEK'],
  ['LHR', 'PVG'],
  ['NRT', 'ARN'],
  ['LAX', 'JFK'],
  ['NRT', 'DEL'],
  ['DFW', 'GRU'],
  ['MAD', 'ATL'],
  ['ORD', 'CAI'],
  ['HKG', 'CDG'],
  ['LAS', 'CDG'],
  ['NRT', 'SVO'],
  ['DEN', 'HNL'],
  ['ORD', 'LAX'],
  ['SIN', 'SEA'],
  ['SYD', 'PEK'],
  ['CAI', 'CPT'],
  ['CUN', 'JFK'],
  ['ORD', 'JFK'],
  ['LHR', 'BOM'],
  ['LAX', 'MEX'],
  ['LHR', 'CPT'],
  ['PVG', 'CGK'],
  ['SYD', 'BOM'],
  ['JFK', 'CPT'],
  ['MAD', 'GRU'],
  ['EZE', 'FCO'],
  ['DEL', 'DXB'],
  ['DXB', 'NRT'],
  ['GRU', 'MIA'],
  ['SVO', 'PEK'],
  ['YYZ', 'ARN'],
  ['LHR', 'YYC'],
  ['HNL', 'SEA'],
  ['JFK', 'EZE'],
  ['EZE', 'LAX'],
  ['CAI', 'HKG'],
  ['SVO', 'SIN'],
  ['IST', 'MCO'],
  ['MCO', 'LAX'],
  ['FRA', 'LAS'],
  ['ORD', 'FRA'],
  ['MAD', 'JFK']
];
const OD_POINTS = ['CDG', 'SFO','HNL','LAX'];

const smallpaths = ['airports', 'ports', 'countries', 'states', 'populated_places'];